name: Build

on:
  push:
    branches: [ adds-ci ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Set up Go 1.22.0 with actions/setup-go@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0' # Updated to version 1.22.0

      # Install dependencies, run tests, and generate coverage report
      - name: Test and Generate Coverage Report
        run: |
          go mod tidy
          go test ./... -coverprofile=coverage.txt -covermode=atomic

      # Upload coverage report to Codecov using v4
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Not required for public repos
          file: ./coverage.txt
          fail_ci_if_error: true # Optional
